version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - develop
  - pull/*
install:
  - nuget restore
build:
  verbosity: detailed
artifacts:
- path: '**/SaferString.*.nupkg'
  name: NuGet Package
environment:
  COVERALLS_REPO_TOKEN:
    secure: IwyKX1L6Kk0Ly/4Z3YJfz2IJmoO5WgkxJBeYXZ7y8gbMflizzv+RNINoV8P8g5pU
after_test: 
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
