-
  branches:
    only:
    - master
  configuration: Release
  platform: Any CPU
  version: 1.0.{build}
  pull_requests:
    do_not_increment_build_number: true
  assembly_info:
    patch: true
    file: '**\VersionInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  before_build:
  - nuget restore
  build:
    project: SaferString.sln
    verbosity: normal
  environment:
    COVERALLS_REPO_TOKEN:
      secure: IwyKX1L6Kk0Ly/4Z3YJfz2IJmoO5WgkxJBeYXZ7y8gbMflizzv+RNINoV8P8g5pU

  artifacts:
  - path: '**/SaferString.*.nupkg'
    name: NuGet Package
  after_test:
  - ps: >-
      $ProgramFiles = (${env:ProgramFiles(x86)}, ${env:ProgramFiles} -ne $null)[0]

      .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"$ProgramFiles\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:$env:APPVEYOR_PROJECT_NAME.Tests/bin/$env:CONFIGURATION/$env:APPVEYOR_PROJECT_NAME.Tests.dll" -output:coverage.xml

      .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  deploy:
    provider: NuGet
    api_key:
      secure: yVcC9zUQ6Xenpgqa4u8YYZ+5Fva1PlkB5rwpfxb1yziyQheqrFow7u6LGZY9wsWI
    skip_symbols: true
    artifact: NuGet Package
-
  branches:
    only:
    - develop
    - pull/*
  configuration: Debug
  platform: Any CPU
  version: 1.0.{build}
  pull_requests:
    do_not_increment_build_number: true
  assembly_info:
    patch: true
    file: '**\VersionInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}-PreRelease'
  before_build:
  - nuget restore
  build:
    project: SaferString.sln
    verbosity: normal
  environment:
    COVERALLS_REPO_TOKEN:
      secure: IwyKX1L6Kk0Ly/4Z3YJfz2IJmoO5WgkxJBeYXZ7y8gbMflizzv+RNINoV8P8g5pU
  artifacts:
  - path: '**/SaferString.*.nupkg'
    name: NuGet Package
  after_test:
  - ps: >-
      $ProgramFiles = (${env:ProgramFiles(x86)}, ${env:ProgramFiles} -ne $null)[0]

      .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"$ProgramFiles\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:$env:APPVEYOR_PROJECT_NAME.Tests/bin/$env:CONFIGURATION/$env:APPVEYOR_PROJECT_NAME.Tests.dll" -output:coverage.xml

      .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
